### ISSUE TITLE
Doesn't work with node 14?

### ISSUE THREAD

**Issue by sugarandmagic** [igoramadas/dedupr#4]
Didn't do anything exciting, just installed globally and passed it a path

<img width="648" alt="image" src="https://user-images.githubusercontent.com/38294284/168818567-602611f9-7e34-4360-a543-8c9dc5d26ba7.png">

**Comment by sugarandmagic** [comment]
Actually I get the same with 12. Any idea @igoramadas?

<img width="652" alt="image" src="https://user-images.githubusercontent.com/38294284/168819120-1a58f71a-4e1e-4d89-b43b-6a5814768b79.png">

**Comment by igoramadas** [comment]
I managed to replicate the issue, which is coming from the "anyhow" module. I couldn't really find a root cause, but fixing it was relatively easy: https://github.com/igoramadas/anyhow/commit/f5c180d83b34cbb14c3aa24e73d1f8cac27dfad8

Version 2.0.2 just released should work.

**Comment by igoramadas** [comment]
PS: the certificate for "carriebeesley.com" has expired... 😜

**Comment by sugarandmagic** [comment]
> PS: the certificate for "carriebeesley.com" has expired... 😜

Haha I know, embarrassing....so little time

**Comment by sugarandmagic** [comment]
> I managed to replicate the issue, which is coming from the "anyhow" module. I couldn't really find a root cause, but fixing it was relatively easy: [igoramadas/anyhow@f5c180d](https://github.com/igoramadas/anyhow/commit/f5c180d83b34cbb14c3aa24e73d1f8cac27dfad8)
> 
> Version 2.0.2 just released should work.

Appreciate it! Sorry I didn't open a pull, so slammed....too slammed to maintain my own website 💀
